import React, { useState } from "react";
import { FiArrowLeft, FiArrowRight, FiCheck, FiChevronDown, FiHeart, FiMinus, FiPlus, FiSearch } from "react-icons/fi";

const Shell = ({ brand, children, action = "Get started" }) => <main className="live-demo"><nav className="demo-nav"><a href="/" className="demo-back"><FiArrowLeft /> Aziz Shahdawala</a><strong>{brand}</strong><div><a href="#features">Features</a><a href="#about">About</a><a className="demo-pill" href="mailto:contact@azizshahda.com">{action}</a></div></nav>{children}<footer><strong>{brand}</strong><span>Interactive portfolio template by Aziz Shahdawala</span><a href="/">Back to portfolio <FiArrowRight /></a></footer></main>;

const Commerce = () => {
  const [filter, setFilter] = useState("All"); const [cart, setCart] = useState(0);
  const products = [{ name: "Linen Field Jacket", type: "Outerwear", price: "₹8,900", tone: "sand" }, { name: "Form Trousers", type: "Essentials", price: "₹5,400", tone: "ink" }, { name: "Soft Structure Shirt", type: "Essentials", price: "₹4,200", tone: "clay" }, { name: "Archive Weekender", type: "Accessories", price: "₹7,600", tone: "olive" }];
  const shown = filter === "All" ? products : products.filter(({ type }) => type === filter);
  return <Shell brand="NOIR & LOOM" action={`Bag · ${cart}`}><section className="commerce-hero"><span>Edition 04 · Everyday form</span><h1>Clothes for a<br />considered life.</h1><p>Natural fabrics. Quiet construction. Pieces designed to be worn, repaired, and remembered.</p><a href="#shop">Explore the collection <FiArrowRight /></a></section><section className="demo-section" id="shop"><header><div><span>New collection</span><h2>Built slowly.<br />Worn often.</h2></div><div className="demo-filters">{["All", "Essentials", "Outerwear", "Accessories"].map((item) => <button className={filter === item ? "active" : ""} onClick={() => setFilter(item)} key={item}>{item}</button>)}</div></header><div className="product-grid">{shown.map((product) => <article key={product.name}><div className={`product-art product-art--${product.tone}`}><button aria-label={`Add ${product.name} to bag`} onClick={() => setCart((value) => value + 1)}><FiPlus /></button><span>{product.type}</span></div><div><h3>{product.name}</h3><p>{product.price}</p></div></article>)}</div></section><section className="commerce-story" id="about"><span>Our standard</span><h2>Fewer pieces.<br />Better decisions.</h2><div><p>Traceable materials, responsible partners, and timeless construction. We share what each piece is made of and where it comes from.</p><p><FiCheck /> Natural and recycled fibres<br /><FiCheck /> Small-batch production<br /><FiCheck /> Repairs for the life of the garment</p></div></section></Shell>;
};

const Property = () => {
  const [budget, setBudget] = useState("Any budget"); const [saved, setSaved] = useState([]);
  const homes = [{ name: "The Courtyard House", place: "Alibaug, Maharashtra", price: "₹3.8 Cr", beds: 4, tone: "coast" }, { name: "Skyline Residence", place: "Worli, Mumbai", price: "₹7.2 Cr", beds: 3, tone: "city" }, { name: "Forest Edge Villa", place: "Lonavala, Maharashtra", price: "₹2.4 Cr", beds: 4, tone: "forest" }];
  const toggle = (name) => setSaved((items) => items.includes(name) ? items.filter((item) => item !== name) : [...items, name]);
  return <Shell brand="HAVEN" action={`Saved · ${saved.length}`}><section className="property-hero"><div><span>Homes with a point of view</span><h1>Find a place<br />that feels like you.</h1><p>Distinctive homes, considered locations, and local advisors who make the search feel human.</p></div><form onSubmit={(event) => event.preventDefault()}><label>Where<input defaultValue="Mumbai & nearby" /></label><label>Budget<select value={budget} onChange={(event) => setBudget(event.target.value)}><option>Any budget</option><option>Under ₹3 Cr</option><option>₹3–5 Cr</option><option>₹5 Cr+</option></select></label><button aria-label="Search properties"><FiSearch /></button></form></section><section className="demo-section property-list" id="features"><header><div><span>Curated for you</span><h2>Homes worth<br />leaving home for.</h2></div><p>{budget === "Any budget" ? "12 handpicked properties" : `Showing homes · ${budget}`}</p></header><div className="home-grid">{homes.map((home) => <article key={home.name}><div className={`home-art home-art--${home.tone}`}><span>For sale</span><button className={saved.includes(home.name) ? "saved" : ""} onClick={() => toggle(home.name)} aria-label={`Save ${home.name}`}><FiHeart /></button></div><h3>{home.name}</h3><p>{home.place}</p><div><strong>{home.price}</strong><span>{home.beds} beds · 3,200 sq ft</span></div></article>)}</div></section><section className="property-advisor" id="about"><div><span>Local guidance</span><h2>Search less.<br />Discover better.</h2></div><p>Tell us what matters beyond bedrooms and budgets. Our advisors curate homes around the way you actually want to live.</p><a href="mailto:contact@azizshahda.com">Schedule a private consultation <FiArrowRight /></a></section></Shell>;
};

const Saas = () => {
  const [annual, setAnnual] = useState(true); const [open, setOpen] = useState(0);
  const faqs = ["Can I connect my existing tools?", "How quickly can a team get started?", "Is enterprise data protected?"];
  const price = annual ? "₹1,490" : "₹1,790";
  return <Shell brand="PULSEOPS" action="Start free"><section className="saas-hero"><div className="saas-badge">Operations, finally in sync</div><h1>Run every workflow<br />from one clear view.</h1><p>PulseOps connects requests, approvals, metrics, and team ownership—without another maze of spreadsheets.</p><div><a className="demo-primary" href="#pricing">Start free <FiArrowRight /></a><a href="#features">See the product</a></div><div className="dashboard-mock"><aside><strong>P</strong>{[1,2,3,4].map((n) => <i key={n} />)}</aside><section><header><div><small>Good morning, Maya</small><h3>Operations overview</h3></div><button>+ New workflow</button></header><div className="metric-row"><span><small>Open requests</small><b>284</b><em>+12%</em></span><span><small>On-time rate</small><b>96.4%</b><em>+3.1%</em></span><span><small>Hours saved</small><b>148</b><em>This month</em></span></div><div className="chart"><i /><i /><i /><i /><i /><i /><i /><i /></div></section></div></section><section className="demo-section saas-features" id="features"><header><div><span>Designed for momentum</span><h2>Less coordination.<br />More progress.</h2></div></header><div>{[["01","Build workflows","Create dependable processes with owners, rules, approvals, and clear next steps."],["02","See the whole system","Track operational health through live metrics, queues, and exceptions."],["03","Automate the routine","Connect tools and remove repetitive handoffs while keeping humans in control."]].map(([n,title,copy]) => <article key={n}><span>{n}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section><section className="saas-pricing" id="pricing"><div><span>Simple pricing</span><h2>Start small.<br />Scale without friction.</h2><button onClick={() => setAnnual((value) => !value)}>{annual ? "Annual billing · save 17%" : "Monthly billing"}</button></div><article><small>Team</small><h3>{price}<span>/user/month</span></h3><p>Everything a growing operations team needs.</p>{["Unlimited workflows","Dashboards and reports","20+ integrations","Priority support"].map((item) => <p key={item}><FiCheck /> {item}</p>)}<a href="mailto:contact@azizshahda.com">Start your workspace</a></article></section><section className="saas-faq" id="about"><h2>Questions, answered.</h2>{faqs.map((question, index) => <button onClick={() => setOpen(open === index ? -1 : index)} key={question}><span>{question}{open === index && <small>{index === 0 ? "Yes. PulseOps is designed around secure integrations and an API-first architecture." : index === 1 ? "Most teams launch their first workflow in a day, then expand progressively." : "Encryption, role-based access, audit logs, and isolated environments are built into the model."}</small>}</span>{open === index ? <FiMinus /> : <FiChevronDown />}</button>)}</section></Shell>;
};

const demos = { commerce: Commerce, property: Property, saas: Saas };
const LiveTemplateDemo = ({ name }) => { const Demo = demos[name]; return Demo ? <Demo /> : <Commerce />; };
export default LiveTemplateDemo;
